#ifndef IWIFICONNECTIONSTATUSPROVIDER_PUBLIC_H
#define IWIFICONNECTIONSTATUSPROVIDER_PUBLIC_H

#include "../01-interface/02-IWiFiConnectionStatusProvider.h"

#endif // IWIFICONNECTIONSTATUSPROVIDER_PUBLIC_H