#ifndef IINTERNETCONNECTIONSTATUSPROVIDER_PUBLIC_H
#define IINTERNETCONNECTIONSTATUSPROVIDER_PUBLIC_H

#include "../01-interface/02-IInternetConnectionStatusProvider.h"

#endif // IINTERNETCONNECTIONSTATUSPROVIDER_PUBLIC_H
