#ifndef COMMANDREGISTRY_H
#define COMMANDREGISTRY_H

#include <StandardDefines.h>

/* Topics */
#define TOPIC_NETWORK "network"
#define TOPIC_WIFI "wifi"
#define TOPIC_INTERNET "internet"
#define TOPIC_TCP_SERVER "tcp_server"
#define TOPIC_MQTT_CLIENT "mqtt_client"
#define TOPIC_REQUEST_MANAGER "request_manager"
#define TOPIC_DEVICE_MANAGER "device_manager"

/* Sender IDs */
#define SENDER_NETWORK 1001
#define SENDER_WIFI 1002
#define SENDER_INTERNET 1003
#define SENDER_TCP_SERVER 1004
#define SENDER_MQTT_CLIENT 1005
#define SENDER_REQUEST_MANAGER 1006
#define SENDER_API_SERVICE 1007

/* Network Commands */
#define COMMAND_RESTART_NETWORK 20001

/* Wifi Commands */
#define COMMAND_RESTART_WIFI 30001
#define COMMAND_START_WIFI 30002
#define COMMAND_STOP_WIFI 30003
#define COMMAND_START_HOTSPOT 30004
#define COMMAND_STOP_HOTSPOT 30005

/* Internet Commands */
#define COMMAND_SYNCHRONIZE_TIME 40001

/* TCP Server Commands */
#define COMMAND_START_TCP_SERVER 50001
#define COMMAND_STOP_TCP_SERVER 50002
#define COMMAND_RESTART_TCP_SERVER 50003


/* MQTT Client Commands */
#define COMMAND_START_MQTT_CLIENT 60001
#define COMMAND_STOP_MQTT_CLIENT 60002
#define COMMAND_RESTART_MQTT_CLIENT 60003
#define COMMAND_ENROLL_DEVICE 60004

/* Request Manager Commands */
#define COMMAND_START_REQUEST_MANAGER 70001
#define COMMAND_STOP_REQUEST_MANAGER 70002
#define COMMAND_RESTART_REQUEST_MANAGER 70003

/* Device Commands */
#define COMMAND_TURN_ON_SWITCH 80001
#define COMMAND_ENROLLMENT_STARTED_STATUS 80002

#endif // COMMANDREGISTRY_H