#ifndef IINTERNETCONNECTIONSTATUSPROVIDER_INCLUDE_H
#define IINTERNETCONNECTIONSTATUSPROVIDER_INCLUDE_H

#include "../internal/03-internet/00-public/01-IInternetConnectionStatusProvider.h"

#endif // IINTERNETCONNECTIONSTATUSPROVIDER_INCLUDE_H