#ifndef INTERNETHEALTHCHECKERTHREAD_INCLUDE_H
#define INTERNETHEALTHCHECKERTHREAD_INCLUDE_H

#include "../internal/07-thread/00-public/02-InternetHealthCheckerThread.h"

#endif // INTERNETHEALTHCHECKERTHREAD_INCLUDE_H