#ifndef IWIFICONNECTIONSTATUSPROVIDER_INCLUDE_H
#define IWIFICONNECTIONSTATUSPROVIDER_INCLUDE_H

#include "../internal/02-wifi/00-public/01-IWiFiConnectionStatusProvider.h"

#endif // IWIFICONNECTIONSTATUSPROVIDER_INCLUDE_H